spring.application.name=reservas-backend
server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=reservas_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=TuPassword123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.maximum-pool-size=10
spring.sql.init.mode=always
app.export.path=./data/reservas.xlsx